name: contentful changes trigger github portfolio's readme/index.md
# This workflow is triggered on pushes to the repository.
on:
  push:
  repository_dispatch:
    types: [publish-event]

# Add concurrency to prevent multiple runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  contentful-update:
    name: Generate and commit readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - run: npm install

      - name: Update content from Contentful
        # parse contentful data and update index.md
        run: node ./contentful-triggered-update.js

        env:
          SPACE_ID: ${{ secrets.SPACE_ID }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        continue-on-error: true

      - name: Check for changes
        id: git-check
        run: |
          git status
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changes exist
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "contentful triggered update: index.md"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      # Trigger CI workflow(ci.yaml) after contentful update
      - name: Trigger CI workflow
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          event-type: contentful-update-complete
